cd('F:\zhourushuang\SEED')
label=load('label.mat');
label=label.label;
for i = 1:15
    cd('F:\zhourushuang\SEED\ExtractedFeatures')
    folder_list=dir('*.mat');
    file_name_session_1=folder_list(i*3-2).name;
    file_name_session_2=folder_list(i*3-1).name;
    file_name_session_3=folder_list(i*3).name;
    data_session_1=load(file_name_session_1);
    data_session_2=load(file_name_session_2);
    data_session_3=load(file_name_session_3);
    feature_session_1=[];
    label_session_1=[];
    feature_session_2=[];
    label_session_2=[];
    feature_session_3=[];
    label_session_3=[];
    
    feature_session_1=[feature_session_1;feature_wrap(data_session_1.de_LDS1)];
    feature_session_1=[feature_session_1;feature_wrap(data_session_1.de_LDS2)];
    feature_session_1=[feature_session_1;feature_wrap(data_session_1.de_LDS3)];
    feature_session_1=[feature_session_1;feature_wrap(data_session_1.de_LDS4)];
    feature_session_1=[feature_session_1;feature_wrap(data_session_1.de_LDS5)];
    feature_session_1=[feature_session_1;feature_wrap(data_session_1.de_LDS6)];
    feature_session_1=[feature_session_1;feature_wrap(data_session_1.de_LDS7)];
    feature_session_1=[feature_session_1;feature_wrap(data_session_1.de_LDS8)];
    feature_session_1=[feature_session_1;feature_wrap(data_session_1.de_LDS9)];
    feature_session_1=[feature_session_1;feature_wrap(data_session_1.de_LDS10)];
    feature_session_1=[feature_session_1;feature_wrap(data_session_1.de_LDS11)];
    feature_session_1=[feature_session_1;feature_wrap(data_session_1.de_LDS12)];
    feature_session_1=[feature_session_1;feature_wrap(data_session_1.de_LDS13)];
    feature_session_1=[feature_session_1;feature_wrap(data_session_1.de_LDS14)];
    feature_session_1=[feature_session_1;feature_wrap(data_session_1.de_LDS15)];
    
    label_session_1=[label_session_1;zeros(size(data_session_1.de_LDS1,2),1)+label(1)];
    label_session_1=[label_session_1;zeros(size(data_session_1.de_LDS2,2),1)+label(2)];
    label_session_1=[label_session_1;zeros(size(data_session_1.de_LDS3,2),1)+label(3)];
    label_session_1=[label_session_1;zeros(size(data_session_1.de_LDS4,2),1)+label(4)];
    label_session_1=[label_session_1;zeros(size(data_session_1.de_LDS5,2),1)+label(5)];
    label_session_1=[label_session_1;zeros(size(data_session_1.de_LDS6,2),1)+label(6)];
    label_session_1=[label_session_1;zeros(size(data_session_1.de_LDS7,2),1)+label(7)];
    label_session_1=[label_session_1;zeros(size(data_session_1.de_LDS8,2),1)+label(8)];
    label_session_1=[label_session_1;zeros(size(data_session_1.de_LDS9,2),1)+label(9)];
    label_session_1=[label_session_1;zeros(size(data_session_1.de_LDS10,2),1)+label(10)];
    label_session_1=[label_session_1;zeros(size(data_session_1.de_LDS11,2),1)+label(11)];
    label_session_1=[label_session_1;zeros(size(data_session_1.de_LDS12,2),1)+label(12)];
    label_session_1=[label_session_1;zeros(size(data_session_1.de_LDS13,2),1)+label(13)];
    label_session_1=[label_session_1;zeros(size(data_session_1.de_LDS14,2),1)+label(14)];
    label_session_1=[label_session_1;zeros(size(data_session_1.de_LDS15,2),1)+label(15)];
    
    feature_session_2=[feature_session_2;feature_wrap(data_session_2.de_LDS1)];
    feature_session_2=[feature_session_2;feature_wrap(data_session_2.de_LDS2)];
    feature_session_2=[feature_session_2;feature_wrap(data_session_2.de_LDS3)];
    feature_session_2=[feature_session_2;feature_wrap(data_session_2.de_LDS4)];
    feature_session_2=[feature_session_2;feature_wrap(data_session_2.de_LDS5)];
    feature_session_2=[feature_session_2;feature_wrap(data_session_2.de_LDS6)];
    feature_session_2=[feature_session_2;feature_wrap(data_session_2.de_LDS7)];
    feature_session_2=[feature_session_2;feature_wrap(data_session_2.de_LDS8)];
    feature_session_2=[feature_session_2;feature_wrap(data_session_2.de_LDS9)];
    feature_session_2=[feature_session_2;feature_wrap(data_session_2.de_LDS10)];
    feature_session_2=[feature_session_2;feature_wrap(data_session_2.de_LDS11)];
    feature_session_2=[feature_session_2;feature_wrap(data_session_2.de_LDS12)];
    feature_session_2=[feature_session_2;feature_wrap(data_session_2.de_LDS13)];
    feature_session_2=[feature_session_2;feature_wrap(data_session_2.de_LDS14)];
    feature_session_2=[feature_session_2;feature_wrap(data_session_2.de_LDS15)];
    
    label_session_2=[label_session_2;zeros(size(data_session_2.de_LDS1,2),1)+label(1)];
    label_session_2=[label_session_2;zeros(size(data_session_2.de_LDS2,2),1)+label(2)];
    label_session_2=[label_session_2;zeros(size(data_session_2.de_LDS3,2),1)+label(3)];
    label_session_2=[label_session_2;zeros(size(data_session_2.de_LDS4,2),1)+label(4)];
    label_session_2=[label_session_2;zeros(size(data_session_2.de_LDS5,2),1)+label(5)];
    label_session_2=[label_session_2;zeros(size(data_session_2.de_LDS6,2),1)+label(6)];
    label_session_2=[label_session_2;zeros(size(data_session_2.de_LDS7,2),1)+label(7)];
    label_session_2=[label_session_2;zeros(size(data_session_2.de_LDS8,2),1)+label(8)];
    label_session_2=[label_session_2;zeros(size(data_session_2.de_LDS9,2),1)+label(9)];
    label_session_2=[label_session_2;zeros(size(data_session_2.de_LDS10,2),1)+label(10)];
    label_session_2=[label_session_2;zeros(size(data_session_2.de_LDS11,2),1)+label(11)];
    label_session_2=[label_session_2;zeros(size(data_session_2.de_LDS12,2),1)+label(12)];
    label_session_2=[label_session_2;zeros(size(data_session_2.de_LDS13,2),1)+label(13)];
    label_session_2=[label_session_2;zeros(size(data_session_2.de_LDS14,2),1)+label(14)];
    label_session_2=[label_session_2;zeros(size(data_session_2.de_LDS15,2),1)+label(15)];
    
    feature_session_3=[feature_session_3;feature_wrap(data_session_3.de_LDS1)];
    feature_session_3=[feature_session_3;feature_wrap(data_session_3.de_LDS2)];
    feature_session_3=[feature_session_3;feature_wrap(data_session_3.de_LDS3)];
    feature_session_3=[feature_session_3;feature_wrap(data_session_3.de_LDS4)];
    feature_session_3=[feature_session_3;feature_wrap(data_session_3.de_LDS5)];
    feature_session_3=[feature_session_3;feature_wrap(data_session_3.de_LDS6)];
    feature_session_3=[feature_session_3;feature_wrap(data_session_3.de_LDS7)];
    feature_session_3=[feature_session_3;feature_wrap(data_session_3.de_LDS8)];
    feature_session_3=[feature_session_3;feature_wrap(data_session_3.de_LDS9)];
    feature_session_3=[feature_session_3;feature_wrap(data_session_3.de_LDS10)];
    feature_session_3=[feature_session_3;feature_wrap(data_session_3.de_LDS11)];
    feature_session_3=[feature_session_3;feature_wrap(data_session_3.de_LDS12)];
    feature_session_3=[feature_session_3;feature_wrap(data_session_3.de_LDS13)];
    feature_session_3=[feature_session_3;feature_wrap(data_session_3.de_LDS14)];
    feature_session_3=[feature_session_3;feature_wrap(data_session_3.de_LDS15)];
    
    label_session_3=[label_session_3;zeros(size(data_session_3.de_LDS1,2),1)+label(1)];
    label_session_3=[label_session_3;zeros(size(data_session_3.de_LDS2,2),1)+label(2)];
    label_session_3=[label_session_3;zeros(size(data_session_3.de_LDS3,2),1)+label(3)];
    label_session_3=[label_session_3;zeros(size(data_session_3.de_LDS4,2),1)+label(4)];
    label_session_3=[label_session_3;zeros(size(data_session_3.de_LDS5,2),1)+label(5)];
    label_session_3=[label_session_3;zeros(size(data_session_3.de_LDS6,2),1)+label(6)];
    label_session_3=[label_session_3;zeros(size(data_session_3.de_LDS7,2),1)+label(7)];
    label_session_3=[label_session_3;zeros(size(data_session_3.de_LDS8,2),1)+label(8)];
    label_session_3=[label_session_3;zeros(size(data_session_3.de_LDS9,2),1)+label(9)];
    label_session_3=[label_session_3;zeros(size(data_session_3.de_LDS10,2),1)+label(10)];
    label_session_3=[label_session_3;zeros(size(data_session_3.de_LDS11,2),1)+label(11)];
    label_session_3=[label_session_3;zeros(size(data_session_3.de_LDS12,2),1)+label(12)];
    label_session_3=[label_session_3;zeros(size(data_session_3.de_LDS13,2),1)+label(13)];
    label_session_3=[label_session_3;zeros(size(data_session_3.de_LDS14,2),1)+label(14)];
    label_session_3=[label_session_3;zeros(size(data_session_3.de_LDS15,2),1)+label(15)];
    dataset_session1.feature=feature_session_1;
    dataset_session1.label=label_session_1+1;
    dataset_session2.feature=feature_session_2;
    dataset_session2.label=label_session_2+1;
    dataset_session3.feature=feature_session_3;
    dataset_session3.label=label_session_3+1;
    cd('F:\zhourushuang\SEED\feature')
    sub=['sub_',num2str(i),'_'];
    save([sub,'session_1','.mat'],'dataset_session1')
    cd('F:\zhourushuang\SEED\feature')
    save([sub,'session_2','.mat'],'dataset_session2')
    cd('F:\zhourushuang\SEED\feature')
    save([sub,'session_3','.mat'],'dataset_session3')
end